spring.application.name=ebank-bot
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
#spring.ai.openai.api.key=
#spring.ai.openai.chat.options.model=
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen3-vl:latest
server.port=8058
spring.ai.mcp.client.streamable-http.connections.customer.url=http://localhost:8056/mcp
spring.ai.mcp.client.streamable-http.connections.ebank.url=http://localhost:8057/mcp
discord.token=
#for discord
discord.gateway-intents=GUILD_MESSAGES,MESSAGE_CONTENT
telegram.token=
eureka.client.jersey.enabled=false